<?php
// $Id: webauth.module 1806 2010-03-18 16:32:08Z ksharp $
/**
 * @file
 * Authenticates users through Stanford WebAuth
 *
 */
 
define('WEBAUTH_DOMAIN', 'stanford.edu');
 
include_once(dirname(__FILE__) . '/WebAuthSession.inc');

/**
 * Implementation of hook_init().
 */
function webauth_init() {
  global $wa_session, $user;
  
  if (variable_get('webauth_nossl', FALSE)) {
    return;
  }
  
  // Setup some variables about forwarding.
  $is_forwarded = (bool) isset($_SERVER['HTTP_X_FORWARDED_HOST']);
  $has_xhost = (bool) strcmp($_SERVER['HTTP_X_FORWARDED_HOST'], 
                             variable_get('webauth_xhost','')) !== 0;
  $is_return_url = (bool) $_GET['q'] == drupal_get_path('module', 'webauth') . '/auth/login';
  $access_denied_page = variable_get('site_403', '');
  
  // Update our access denied page.
  if ($access_denied_page != 'webauth/403') {
    variable_set('site_403', 'webauth/403');
    variable_set('webauth_403', $access_denied_page);
  } 
                             
  // If we are running behind a proxy server, save the xhost value in our drupal variables.
  if ($is_forwarded && !$has_xhost) {
    variable_set('webauth_xhost', $_SERVER['HTTP_X_FORWARDED_HOST']);
  }
	
  // Start new WebAuthSession.
  if (!$is_return_url) {
    $wa_session = new WebAuthSession();
    if (!$wa_session->isValidSession()) {
      user_logout();
      header("Expires: Sun, 19 Nov 1978 05:00:00 GMT");
      header("Cache-Control: no-store, no-cache, must-revalidate"); 
    }
  }
  
}

/**
 * Implementation of hook_menu().
 */
function webauth_menu() {
  $items = array();
  
  // Setup our authentication URL
  $path = variable_get('webauth_path', conf_path() . '/webauth') . '/login';
  
  $items[$path] = array(
    'page callback' => 'webauth_return',
    'access arguments' => array('access content'),
  );
 
  $items['webauth/403'] = array(
    'page callback' => 'webauth_error_page',
    'access arguments' => array('access content'),
  );
  
  $items['admin/settings/webauth'] = array(
    'title' => 'WebAuth',
    'description' => 'Authenticate through Stanford WebAuth',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('webauth_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'webauth.admin.inc',
  );
  
  $items['admin/settings/webauth/settings'] = array(
    'title' => 'WebAuth Settings',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );

  $items['admin/settings/webauth/users'] = array(
    'title' => 'Users',
    'description' => 'Edit the groups that can use Webauth for content access.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('webauth_admin_users'),
    'access arguments' => array('administer site configuration'),
    'file' => 'webauth.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );

  $items['admin/settings/webauth/groups'] = array(
    'title' => 'Groups',
    'description' => 'Edit the groups that can use Webauth for content access.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('webauth_admin_groups'),
    'access arguments' => array('administer site configuration'),
    'file' => 'webauth.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 * Handle 403 errors.
 */
function webauth_error_page() {
  global $wa_session, $user;
  if (!$wa_session) {
    $wa_session = new WebAuthSession();
  }
  if ($user->uid) {
    die('uphere');
    drupal_goto(variable_get('webauth_403', ''));
  }
  else {
    //unset($_SESSION['wa_return_url']['query']);
    //header('HTTP/1.1 200 OK');
    $_REQUEST['destination'] = $_GET['q'];
    $wa_session->getWeblogin();
  }
}

/**
 * Function to return from webauth login from.
 */
function webauth_return() {
  global $wa_session, $user;
  
  $wa_session = new WebAuthSession();
  //print_r($wa_session);

  if (!$user->uid) {
    if ($wa_session->isValidSession()) {
      $form_state = array();
      $form_state['values']['name'] = $wa_session->getSessionData('wa_remote_user');
      $form_state['values']['pass'] = 'dummy';
      $form_state['weblogin']['server'] = variable_get('webauth_domain', WEBAUTH_DOMAIN);
      drupal_execute('user_login', $form_state);
    }
    else {
      drupal_set_message(print_r($wa_session, TRUE));
      $wa_session->getWeblogin();
    }
  }
  
  if (!$wa_session->isValidSession()) {
    drupal_set_message('Unknown error occurred.');
  }
  
  drupal_goto($wa_session->getReturnUrl());
}

/**
 * Implementation of hook_theme().
 */
function webauth_theme($existing, $type, $theme, $path) {
  return array(
    'webauth_htaccess' => array(
      'arguments' => array('groups' => NULL, 'require_valid_user' => NULL, 'users' => NULL, 'rewrite_url' => NULL),
      'template' => 'webauth_htaccess',
    ),
  );
}

/**
 * Implementation of hook_form_alter().
 */
function webauth_form_alter(&$form, &$form_state, $form_id) {
  global $user, $base_url, $wa_session;

  if (!$wa_session) {
    $wa_session = new WebAuthSession();
  }
  
  switch ($form_id) {
    case 'user_profile_form':
      $account = $form['_account']['#value'];
      if ($user->uid == $account->uid) {
        // If we are editing our own account.
        if (!empty($account->roles)) {
          if (in_array(variable_get('webauth_default_role', ''), array_keys($account->roles))) {
            // Hide elements for SUNet Users.
            $form['account']['name']['#type'] = 'hidden';
            $form['account']['name']['#value'] = $form['account']['name']['#default_value'];
            $form['account']['pass']['#type'] = 'hidden';
          }
        }
      }
      break;
    case 'user_login_block':
    case 'user_login':
      if (isset($form_state['weblogin']['server'])) {
        $form['#validate'] = array(
          'user_login_name_validate', 
          'webauth_login_validate', 
          'user_login_final_validate',
        );
      }

      // Build a link to wa_login.
      $secure_base_url = str_replace('http:', 'https:', $base_url);
      $webauth_login = $wa_session->getLoginUrl($_GET['q']);
      $wa_url = l(variable_get('webauth_link_text','SUNetID'), $webauth_login);
      $form['webauth_link'] = array(
        '#prefix' => '<div id="webauth-link">',  // make it themable
        '#value' => $wa_url,
        '#suffix' => '</div>',
        '#weight' => -10
      );

      if ($form_id == 'user_login_block') {
        $allow_local = variable_get('webauth_allow_local', TRUE);
        if (!$allow_local) {
          unset($form['name']);
          unset($form['pass']);
          unset($form['submit']);
          unset($form['links']);
        }
      }
      break;
  }
}


/**
 * Implementation of hook_user().
 */
function webauth_user($op, &$edit, &$account, $category = NULL) {
  switch ($op) {
    case 'login':
      // If we are a local account, check for roles and re-grant new roles.
      if (in_array(variable_get('webauth_default_role', ''), array_keys($account->roles))) {
        webauth_grant_roles($edit, $account);
      }
      break;
    case 'insert':
      webauth_update_fields($edit, $account);
      webauth_grant_roles($edit, $account);
      break;
    case 'logout':
      if (isset($_COOKIE['webauth_at'])) {
        //unset($_COOKIE['webauth_at']);
        //setcookie('webauth_at', '', time() - 3600, '/');
      }
  }
}

function webauth_update_fields(&$edit, &$account) {
  global $wa_session;
  if (!$wa_session) {
    $wa_session = new WebAuthSession();
  }
  
  $mail = $wa_session->getSessionData('wa_ldap_mail');
  $mail =  isset($mail) ? $mail : $account->name;
  db_query("UPDATE {users} SET mail = '%s' WHERE uid = %d", $mail, $account->uid);

}

function webauth_grant_roles(&$edit, &$account) {
  global $wa_session;
  if (!$wa_session) {
    $wa_session = new WebAuthSession();
  }
  
  if ($wa_session->isValidSession()) {
    $groups = $wa_session->getLdapGroups();
    $new = array('roles' => $account->roles);
    
    // Add SUNet User role for all valid users.
    $default_name = db_result(db_query("SELECT name FROM {role} WHERE rid = %d", variable_get('webauth_default_role', '')));
    $new['roles'][variable_get('webauth_default_role', '')] = $name;
    
    if (!empty($groups)) {
      // Unserialize data.
      $data = unserialize($account->data);
      $data = is_array($data) ? $data : array(); 

      // Find all roles that are in the webauth_roles table and add any ones that user is in.
      $result = db_query("SELECT r.rid, r.name, wr.wa_group AS `group` FROM {webauth_roles} wr INNER JOIN {role} r ON r.rid = wr.rid");
      while ($role = db_fetch_object($result)) {
        if (in_array($role->group, $groups)) {
          $new['roles'][$role->rid] = $role->name;
          $data['webauth_assigned_roles'][$role->rid] = $role->name;
        }
        else {
          // Remove user from groups that they are no longer in.
          if (!empty($data['webauth_assigned_roles']) && in_array($role->rid, array_keys($data['webauth_assigned_roles']))) {
            unset($new['roles'][$role->rid]);
            unset($data['webauth_assigned_roles'][$role->rid]);
          }
        }
      }
      $account->data = serialize($data);
    }
    user_save($account, $new);
  }
}

function webauth_login_validate($form, &$form_state) {
  global $wa_session;
  
  if ($wa_session->isValidSession()) {
    user_external_login_register($form_state['values']['name'] . '@' . $form_state['weblogin']['server'], 'webauth');
    user_authenticate_finalize($form_state['values']);
  }
}

/**
 * Function to write out our .htaccess file.
 */
function webauth_write_htaccess() {
  global $wa_session;

  if (!$wa_session) {
    $wa_session = new WebAuthSession();
  }

  $groups = array();
  $user_list = '';
  $rewrite_url = '';
  
  // Get all the available groups
  $result = db_query("SELECT DISTINCT(wa_group) AS `group` FROM {webauth_roles} WHERE rid > 2");
  while ($group = db_result($result)) {
    $groups[] = $group;
  }
  
  $users = explode("\n", variable_get('webauth_require_users', ''));
  foreach ($users as $u) {
    $user_list .= trim($u) . ' ';
  }

  
  if (!variable_get('clean_url', 0)) {
    $path = $wa_session->getLoginUrl();
    $new_path = base_path() . '?q=' . variable_get('webauth_path', conf_path() . '/webauth') . '/login';
    $rewrite_url  = "RewriteEngine on\n";
    $rewrite_url .= "RewriteCond %{REQUEST_FILENAME} !-f\n";
    $rewrite_url = 'RewriteRule login(.*)$' . $new_path . '$1 [L,R=301]';    
  }

  // Theme contents of the .htaccess file.
  $htaccess_file = theme('webauth_htaccess', $groups, variable_get('webauth_require_valid_user', 0), $user_list, $rewrite_url);
  
  // Get the path or create it inside the files dir.
  $webauth_path = variable_get('webauth_path', conf_path() . '/webauth');

  // Set .htaccess file location
  $webauth_htaccess = $webauth_path . '/.htaccess';

  // If webauth dir doesn't exist yet, create it.      
  if (@is_dir($webauth_path) === FALSE) {
    // Create dir.
    mkdir($webauth_path, 0755);
    
    // Copy necessary check.php file over.
    $default_check_file = drupal_get_path('module', 'webauth') . '/default/check.php';
    copy($default_check_file, $webauth_path . '/check.php');
  }
  
  // Save .htaccess file to location.
  $fp = fopen($webauth_htaccess, 'w');
  fwrite($fp, $htaccess_file);
  fclose($fp);
}
